# Generated by Django 4.2.1 on 2023-05-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('position_top', models.PositiveIntegerField()),
                ('position_left', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StickyNoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='analytics.stickynote')),
            ],
        ),
    ]
