# Generated by Django 4.2.1 on 2023-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_board_boardstickynote_board_sticky_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardstickynote',
            name='given_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
